places = [{"placeName":"Abu Simbel","descrip":"These two temples were built as a monument to Ramses II","latitude":22.336823,"longitude":31.625532},
{"placeName":"Bent Pyramid","descrip":"The Bent Pyramid has an unsual shape compared to most contemporary pyramids, thus giving it its name","latitude":29.7904,"longitude":31.2093},
{"placeName":"Colossi of Memnon","descrip":"These statues were built in the likeness of Amenhotep III","latitude":25.7206,"longitude":32.6105},
{"placeName":"Deir el Bahri","descrip":"This site, built for the remains of Mentuhotep II, contained numerous other royal bodies","latitude":25.7373,"longitude":32.6077},
{"placeName":"Deir el Medina","descrip":"This site contained the remains of many workers who helped create the Valleys of Kings and Queens","latitude":25.728,"longitude":32.6014},
{"placeName":"Edfu Temple","descrip":"This temple was built in dedication to the Egyptian god Horus","latitude":24.978548,"longitude":32.87582},
{"placeName":"Karnak Temple","descrip":"This temple took over 2,000 years to fully construct","latitude":25.719595,"longitude":32.655807},
{"placeName":"Kom Ombo","descrip":"Unusually, this site was formed by two separate temples","latitude":24.479,"longitude":32.9461},
{"placeName":"Luxor Temple","descrip":"Many pharaohs were coronated here throughout Egyptian history","latitude":25.6995,"longitude":32.6391},
{"placeName":"The Great Sphinx","descrip":"Located near Cairo, this is one of the most iconic landmarks in both Egypt and the world","latitude":29.97535,"longitude":31.1375},
{"placeName":"The Saqqara Pyramid","descrip":"This is location of the oldest known pyramid in Egypt","latitude":29.8713,"longitude":31.2168},
{"placeName":"Valley of Kings","descrip":"Numerous tombs, including that of Tutankhamen, were found here","latitude":25.746424,"longitude":32.605309},
{"placeName":"Valley of Queens","descrip":"This is where the wives of the pharaohs in the Valley of Kings were buried","latitude":25.7286,"longitude":32.5929},
{"placeName":"Philae Temple","descrip":"This site's construction concluded during the period of history where Egyptian was under Roman rule","latitude":24.0127,"longitude":32.8775},
{"placeName":"Temple of Hathor","descrip":"Like the Philae Temple, this site was built during the time Egypt was under Roman rule","latitude":26.1419,"longitude":32.6702},
{"placeName":"Medinet Habu","descrip":"This temple was dedicated to Ramses III","latitude":25.71848379,"longitude":32.6004176},
{"placeName":"Memphis","descrip":"This was the original capital of Egypt","latitude":29.84312996,"longitude":31.25256566},
{"placeName":"Hatshepsut's Obelisk","descrip":"Though it was began under the rule of Hatshepsut, this obelisk was never fully constructed","latitude":24.0769,"longitude":32.8954},
{"placeName":"Ramesseum","descrip":"This is where the body of Ramses II was originally located","latitude":25.72333044,"longitude":32.60633091},
{"placeName":"Temple of Khnum","descrip":"As the name suggests, this temple was dedicated to the Egyptian god of creation, Khnum","latitude":25.2934,"longitude":32.5563}];
